service: aws-python-simple-http-endpoint

package:
  exclude:
    - env
    - stockfish_mac

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  profile: serverless

functions:
  getMove:
    handler: handler.endpoint
    events:
      - http:
          path: move
          method: get
