service: aws-python-simple-http-endpoint

package:
  exclude:
    - env
    - stockfish_mac

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  profile: serverless
  environment:
    ENV: PROD

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
